name: GitHub Metrics

on:
  schedule:
    - cron: "0 */12 * * *" 
  workflow_dispatch:

jobs:
  metrics:
    runs-on: ubuntu-latest
    steps:
      - name: Generate metrics
        uses: lowlighter/metrics@latest
        with:

          token: ${{ secrets.METRICS_TOKEN }}
          user: SuvidhJ
          filename: metrics.svg
          template: classic
          base: header, activity, community, repositories, metadata
          config_timezone: UTC

          plugin_achievements: yes
          plugin_achievements_display: detailed
          plugin_achievements_threshold: C
          plugin_achievements_secrets: yes
          plugin_achievements_limit: -1


          plugin_languages: yes
          plugin_languages_indepth: true
          plugin_languages_ignored: html, css
          plugin_languages_details: bytes-size, percentage
          plugin_languages_limit: 12

          plugin_followup: yes
          plugin_followup_sections: repositories, issues, prs

          plugin_notable: yes
          plugin_notable_repositories: yes

          plugin_lines: yes
