name: Recent GitHub Activity

on:
  schedule:
    - cron: "*/60 * * * *" 
  workflow_dispatch:

jobs:
  update-readme:
    runs-on: ubuntu-latest
    steps:
      - uses: Readme-Workflows/recent-activity@v2.4.1
        with:
          GITHUB_TOKEN: ${{ secrets.SNAKE_TOKEN }}
          MAX_LINES: 10
