name: Recent GitHub Activity

on:
  schedule:
    - cron: "*/60 * * * *" 
  workflow_dispatch:
  
permissions:
  contents: read
  issues: read
  pull-requests: read

jobs:
  update-readme:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Update recent activity
        uses: Readme-Workflows/recent-activity@v2.4.1
        with:
          GH_USERNAME: SuvidhJ
          CONFIG_FILE: .github/recent-activity.config.yml
