name: Recent GitHub Activity

on:
  schedule:
    - cron: "*/60 * * * *" 
  workflow_dispatch:
  
permissions:
  contents: read
  issues: read
  pull-requests: read

jobs:
  update-readme:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          fetch-depth: 0

      - name: Configure git
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git config --global --add safe.directory "$GITHUB_WORKSPACE"

      - name: Update recent activity
        uses: Readme-Workflows/recent-activity@v2.4.1
        with:
          GH_USERNAME: SuvidhJ
          CONFIG_FILE: .github/recent-activity.config.yml
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
